version: '3'
services:
  todoapp:
    container_name: todoapp  #name of the container 
    restart: always # always start container if it stops
    build: ./ # builds image from Dockerfile in currenct dirrctory
    # volumes:
    #   - ./:/app # mounts local folder into container (removed to avoid overwriting node_modules)
    links:
      - mongo # links todoapp to mongo (this is an old way usually through networking now)
    ports:
      - 80:3000 
    #   - NODE_ENV=development  #sets environment variable
    #   - PORT=3000
    # depends_on: 
    #   - mongo  


  mongo: 
    image: mongo #pulls mongodb official image
    container_name: mongo  # names the it as mongo i.e the container name
    ports:
      - "27017:27017"  # maps mongodb default port 

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - todoapp

 